import React, { useEffect, useState } from 'react';
import { Html5QrcodeScanner } from 'html5-qrcode';
import { db, auth } from '../../services/firebase';
import { collection, query, where, getDocs, addDoc } from 'firebase/firestore';
import './AttendanceScanner.css';

const AttendanceScanner = () => {
  const [scanResult, setScanResult] = useState(null);
  const [scanError, setScanError] = useState(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const scanner = new Html5QrcodeScanner('reader', {
      qrbox: {
        width: 250,
        height: 250,
      },
      fps: 5,
    });

    const onScanSuccess = async (decodedText) => {
      // The decoded text should be the qrCodeString generated by the teacher
      scanner.clear();
      setScanResult(decodedText);
      await handleCheckIn(decodedText);
    };

    const onScanError = (err) => {
      // Ignore scan errors, as they happen continuously when no QR is found
    };

    scanner.render(onScanSuccess, onScanError);

    return () => {
      scanner.clear().catch(e => console.error("Failed to clear scanner", e));
    };
  }, []);

  const handleCheckIn = async (qrCodeString) => {
    setLoading(true);
    setScanError(null);
    try {
      const user = auth.currentUser;
      if (!user) throw new Error("Not authenticated");

      // 1. Find the active session with this QR string
      const q = query(collection(db, 'attendance_sessions'), 
        where('qrCodeString', '==', qrCodeString),
        where('active', '==', true)
      );
      
      const snapshot = await getDocs(q);
      
      if (snapshot.empty) {
        throw new Error("Invalid or expired QR Code. Please wait for the teacher's screen to refresh and try again.");
      }

      const sessionDoc = snapshot.docs[0];
      const sessionData = sessionDoc.data();
      
      // 2. Check if expired
      if (new Date() > sessionData.expiresAt.toDate()) {
         throw new Error("This QR Code has expired. Please scan the new one on the screen.");
      }

      // 3. Check if already checked in
      const logQ = query(collection(db, 'attendance_logs'),
        where('sessionId', '==', sessionDoc.id),
        where('studentId', '==', user.uid)
      );
      const logSnap = await getDocs(logQ);
      if (!logSnap.empty) {
        throw new Error("You are already checked in for this session.");
      }

      // 4. Log attendance
      await addDoc(collection(db, 'attendance_logs'), {
        sessionId: sessionDoc.id,
        courseId: sessionData.courseId,
        studentId: user.uid,
        studentEmail: user.email,
        studentName: user.displayName || user.email,
        timestamp: new Date(),
        status: 'present'
      });

      setScanResult("Successfully checked in!");
      
    } catch (err) {
      console.error(err);
      setScanError(err.message);
    }
    setLoading(false);
  };

  return (
    <div className="attendance-scanner-container">
      <div className="glass-panel">
        <h2>Scan to Check-In</h2>
        <p className="subtitle">Point your camera at the QR code on the board.</p>
        
        {!scanResult && !scanError && !loading && (
          <div className="scanner-wrapper">
             <div id="reader"></div>
          </div>
        )}

        {loading && <div className="loading-state">Verifying Attendance...</div>}

        {scanError && (
          <div className="scan-error">
            <span className="icon">
               <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="#ef4444" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>
            </span>
            <p>{scanError}</p>
            <button className="liquid-btn primary-btn" onClick={() => window.location.reload()}>Try Again</button>
          </div>
        )}

        {scanResult && !scanError && !loading && (
          <div className="scan-success">
            <span className="icon">
              <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="#10b981" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg>
            </span>
            <p>{scanResult}</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default AttendanceScanner;
